name: Update Main Branch

on:
  push:
    branches:
      - release

jobs:
  update-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Main Branch
        run: |
          git checkout main
          git merge --no-ff origin/release
          git push origin main
