name: PRs to release
on: 
  pull_request:
    branches: [release]
    types: [closed]
jobs:
  merge-release-back-to-main:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Merge release back to main
      run: |
          git fetch --unshallow
          git checkout main
          git pull
          git merge --no-ff release -m "Auto-merge release back to main"
          git push
